### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [kennycason/genetic_draw#2]
Hello, under what license is this project released under ? Thank-you.

**Comment by kennycason** [comment]
I made it MIT with only one optional condition to give links/credit if you found the code inspirational. But it's optional. Enjoy the code and do as you please! :)

https://github.com/kennycason/genetic_draw/blob/master/LICENSE

**Comment by kennycason** [comment]
I found a better license that fits my desires. "do what you want, but provide attribution." I will be changing to that.
